sudo: required

group: deprecated-2017Q3

language: scala
scala:
   - 2.11.8

services:
  - docker

#install:
#  - ./tools/travis/setup.sh

#script:
#  - travis_wait 66 ./tools/travis/build.sh


#    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
#    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

cache:
  directories:
    - $HOME/docker

#before_install:
  # Load cached docker images
#  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi

#dependencies:
#  cache_directories:
#    - "~/docker"

#  override:
#    - if [[ -e ~/docker/image.tar ]]; then docker load -i ~/docker/image.tar; fi
    #- docker build --rm=false -t circleci/elasticsearch .
    #- mkdir -p ~/docker; docker save circleci/elasticsearch > ~/docker/image.tar

#jobs:
#  include:
#    - stage: build docker image
#      script:
#      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
#      - docker build -t travis-ci-build-stages-demo .
#      - docker images
#      - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/travis-ci-build-stages-demo
#      - docker push $DOCKER_USERNAME/travis-ci-build-stages-demo
#    - stage: test
#      script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt
#    - script: docker run --rm $DOCKER_USERNAME/travis-ci-build-stages-demo cat hello.txt

jobs:
  include:
    - stage: set up
      script: ./tools/travis/setup.sh
    - stage: deploy
      script: ./tools/travis/build.sh
